### ISSUE TITLE
Improve documentation on all repositories

### ISSUE THREAD

**Issue by levinmr** [18F/analytics-reporter#780]
README documentation is out of date on all repos.  This needs to be updated to facilitate new developers onboarding for the project and also to help inform anyone who is browsing these public repositories.
```[tasklist]
### Tasks
- [ ] Update README analytics-reporter
- [ ] Update README analytics-reporter-api
- [ ] Update README analytics.usa.gov
```
